# Generated by Django 4.2.3 on 2024-05-23 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('resigned', 'Resigned')], default='active', max_length=20)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hrm_id', models.CharField(help_text='Payee ID obtained from Zoho people', max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_joining', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tds_legal_name', models.CharField(choices=[('technical-consultants', 'Technical Consultants'), ('professional-consultant', 'Professional Consultant'), ('employment', 'Employment'), ('apprentices', 'Apprentices')], max_length=50, unique=True)),
                ('tds_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PayRecordRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('month', models.CharField(blank=True, max_length=15, null=True)),
                ('account_number', models.CharField(blank=True, max_length=16, null=True)),
                ('tds_percentage', models.FloatField(blank=True, null=True)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.payee')),
            ],
        ),
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('month', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=16, null=True)),
                ('pay_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.payrecordregister')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.payee')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label', models.CharField(max_length=50)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.payee')),
            ],
        ),
        migrations.AddField(
            model_name='payee',
            name='tds_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.tds', to_field='tds_legal_name'),
        ),
        migrations.AddField(
            model_name='payee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, max_length=10, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('micr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_address', models.TextField(blank=True, null=True)),
                ('payee_acknowledgement', models.BooleanField(default=False)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.payee')),
            ],
        ),
    ]
