# Generated by Django 4.2.3 on 2023-07-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
