# Generated by Django 4.2.3 on 2024-05-27 13:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import employees.upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetailsAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('bank_details_screenshot', models.ImageField(upload_to=employees.upload_helpers.user_directory_path, validators=[employees.upload_helpers.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_acknowledgement', to='employees.payee')),
            ],
        ),
    ]
