# Generated by Django 4.2.3 on 2024-05-28 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_bankdetailsack'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrecordregister',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrecordregister',
            name='account_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payrecordregister',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrecordregister',
            name='branch_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrecordregister',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrecordregister',
            name='micr_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrecordregister',
            name='record_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrecordregister',
            name='swift_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrecordregister',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='payrecordregister',
            unique_together={('payee', 'month')},
        ),
    ]
