# Generated by Django 4.2.3 on 2024-05-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_payrecordregister_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
