# Generated by Django 4.2.3 on 2023-07-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_department_remove_employee_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
