# Generated by Django 4.2.3 on 2024-05-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_payrecordregister_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('removed', 'Removed'), ('disengaged', 'Disengaged')], default='active', help_text='Select the current status of the payee. "Active" for currently working, "Removed" for those who have been removed from their position, and "Disengaged" for those who are no longer engaged with the company.', max_length=20),
        ),
    ]
