# Generated by Django 4.2.3 on 2023-08-01 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('Technical consultants', 'Technical consultants'), ('Professional Consultant', 'Professional Consultant'), ('Employment', 'Employment'), ('Intern', 'Intern')], max_length=50, unique=True)),
                ('tds_percentage', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='full_name',
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.tds', to_field='employment_type'),
        ),
    ]
