# Generated by Django 4.2.3 on 2024-05-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_payee_is_deleted_alter_payee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='payee_acknowledgement',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
