# Generated by Django 4.2.3 on 2023-08-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_tds_rename_name_employee_full_name_wage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_joining',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, max_length=10, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('micr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_address', models.TextField(blank=True, null=True)),
                ('employee_acknowledgement', models.CharField(choices=[('Pending', 'PENDING'), ('Confirmed', 'CONFIRMED'), ('Disapproved', 'DISAPPROVED')], default='Pending', max_length=50, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
