# Generated by Django 4.2.3 on 2024-06-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_bankdetails_payee_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetailsack',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankdetailsack',
            name='correction_comments',
            field=models.TextField(blank=True, help_text='Please specify any mistaken areas found in the bank details.', null=True),
        ),
    ]
