# Generated by Django 4.2.3 on 2024-06-05 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_bankdetailsack_correction_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrecord',
            name='record_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrecord',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='payrecord',
            unique_together={('payee', 'month')},
        ),
    ]
