# Generated by Django 4.2.3 on 2024-04-24 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0007_earning_delete_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(default=1, help_text='Employee ID obtained from Zoho people', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('resigned', 'Resigned')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='employee_acknowledgement',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('disapproved', 'Disapproved')], default='pending', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='earning',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='earning',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tds',
            name='employment_type',
            field=models.CharField(choices=[('technical-consultants', 'Technical Consultants'), ('professional-consultant', 'Professional Consultant'), ('employment', 'Employment'), ('intern', 'Intern')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tds',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tds',
            name='tds_percentage',
            field=models.FloatField(),
        ),
    ]
