# Generated by Django 4.2.11 on 2024-08-08 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_payrecord_record_created_alter_payrecord_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'verbose_name': 'Bank Detail', 'verbose_name_plural': 'Bank Details'},
        ),
        migrations.AlterModelOptions(
            name='bankdetailsack',
            options={'verbose_name': 'Bank Detail Acknowledgement', 'verbose_name_plural': 'Bank Detail Acknowledgements'},
        ),
        migrations.AlterModelOptions(
            name='payee',
            options={'verbose_name': 'Payee', 'verbose_name_plural': 'Payees'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='payrecord',
            options={'verbose_name': 'Pay Record', 'verbose_name_plural': 'Pay Records'},
        ),
        migrations.AlterModelOptions(
            name='payrecordregister',
            options={'verbose_name': 'Pay Record Register', 'verbose_name_plural': 'Pay Record Registers'},
        ),
        migrations.AlterModelOptions(
            name='tds',
            options={'verbose_name': 'Tax Deducted at Source', 'verbose_name_plural': 'Tax Deducted at Source'},
        ),
        migrations.CreateModel(
            name='PayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('due', 'pay record entry creation in due'), ('in_progress', 'pay record entry creation in progress'), ('completed', 'pay record entry creation completed')], default='due', max_length=20)),
            ],
            options={
                'verbose_name': 'Pay Run',
                'verbose_name_plural': 'Pay Runs',
                'unique_together': {('month', 'year')},
            },
        ),
    ]
