# Generated by Django 4.2.11 on 2024-08-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_payrecord_record_created_alter_payrecord_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('due', 'pay record entry creation in due'), ('in_progress', 'pay record entry creation in progress'), ('completed', 'pay record entry creation completed')], default='due', max_length=20)),
                ('tds_percentage', models.FloatField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.payee')),
            ],
            options={
                'unique_together': {('payee', 'month', 'year')},
            },
        ),
    ]
