# Generated by Django 4.2.3 on 2024-05-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_remove_bankdetails_id_remove_earning_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tds',
            name='employment_type',
            field=models.CharField(choices=[('technical-consultants', 'Technical Consultants'), ('professional-consultant', 'Professional Consultant'), ('employment', 'Employment'), ('apprentices', 'Apprentices')], max_length=50, unique=True),
        ),
    ]
