# Generated by Django 4.2.3 on 2024-05-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_payrecordregister_payrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Payee',
        ),
        migrations.RenameModel(
            old_name='Earning',
            new_name='Payment',
        ),
        migrations.RenameField(
            model_name='bankdetails',
            old_name='employee',
            new_name='payee',
        ),
        migrations.RenameField(
            model_name='bankdetails',
            old_name='employee_acknowledgement',
            new_name='payee_acknowledgement',
        ),
        migrations.RenameField(
            model_name='payee',
            old_name='employment_type',
            new_name='tds_type',
        ),
        migrations.RenameField(
            model_name='payee',
            old_name='emp_id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='payee',
            old_name='emp_code',
            new_name='hrm_id',
        ),
        migrations.AlterField(
            model_name='payee',
            name='hrm_id',
            field=models.CharField(
                help_text='Payee ID obtained from Zoho people',
                max_length=100),
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='employee',
            new_name='payee',
        ),
        migrations.RenameField(
            model_name='payrecord',
            old_name='employee',
            new_name='payee',
        ),
        migrations.RenameField(
            model_name='payrecordregister',
            old_name='employee',
            new_name='payee',
        ),
        migrations.RenameField(
            model_name='tds',
            old_name='employment_type',
            new_name='job_category',
        ),
    ]
