# Generated by Django 4.2.3 on 2024-05-19 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_rename_employee_payee_rename_earning_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='hrm_id',
            field=models.CharField(help_text='Payee ID obtained from Zoho people', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payee',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
