# Generated by Django 4.2.11 on 2026-02-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wikicategory_wikipage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='tax_worksheet',
            field=models.FileField(blank=True, null=True, upload_to='tax_worksheets/'),
        ),
    ]
