# Generated by Django 4.2.11 on 2026-02-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
