# Generated by Django 4.2.11 on 2026-02-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payslip_basic_salary_payslip_hra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='hra',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='other_allowance',
        ),
    ]
