ARG BASE_IMAGE

FROM $BASE_IMAGE

ARG YGAG_PIP_PRIVATE_REPO_URL

WORKDIR /ygag

ADD requirements.txt /ygag/requirements.txt

# Add packages to the image
ADD ./deployment/app/packages/apk/req /ygag/packages/apk/req

RUN apk update && \
    apk add --no-cache --no-network --virtual .build-deps /ygag/packages/apk/req/* && \
    pip3.11 install --extra-index-url=$YGAG_PIP_PRIVATE_REPO_URL --no-cache-dir -r requirements.txt && \
    apk del .build-deps && \
    rm -rf /ygag/packages/apk
