FROM python:3.11.4-alpine3.17

RUN adduser -h /ygag -D ygag

WORKDIR /ygag

RUN mkdir logs
RUN chown -R ygag /ygag

ENV PATH "$PATH:/ygag/.local/bin"

# Add packages to the image
ADD ./deployment/app/packages/apk/base /ygag/packages/apk/base

# Install dependencies
RUN apk update && \
    apk add --no-cache --no-network /ygag/packages/apk/base/* && \
    pip3.11 install --no-cache-dir --upgrade pip==22.0.4 && \
    rm -rf /ygag/packages/apk