# Generated by Django 4.2.11 on 2024-09-04 05:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import payees.upload_helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tds_legal_name', models.CharField(choices=[('technical-consultants', 'Technical Consultants'), ('professional-consultant', 'Professional Consultant'), ('employment', 'Employment'), ('apprentices', 'Apprentices')], max_length=50, unique=True)),
                ('tds_percentage', models.FloatField()),
            ],
            options={
                'verbose_name': 'Tax Deducted at Source',
                'verbose_name_plural': 'Tax Deducted at Source',
            },
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed'), ('disengaged', 'Disengaged')], default='active', help_text='Select the current status of the payee. "Active" for currently working, "Removed" for those who have been removed from their position, and "Disengaged" for those who are no longer engaged with the company.', max_length=20)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hrm_id', models.CharField(help_text='Payee ID obtained from Zoho people', max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_joining', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tds_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payees.tds', to_field='tds_legal_name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payee',
                'verbose_name_plural': 'Payees',
            },
        ),
        migrations.CreateModel(
            name='BankDetailsAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('bank_details_screenshot', models.ImageField(upload_to=payees.upload_helpers.user_directory_path, validators=[payees.upload_helpers.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('is_approved', models.BooleanField(default=False)),
                ('correction_comments', models.TextField(blank=True, help_text='Please specify any mistaken areas found in the bank details.', null=True)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_acknowledgement', to='payees.payee')),
            ],
            options={
                'verbose_name': 'Bank Detail Acknowledgement',
                'verbose_name_plural': 'Bank Detail Acknowledgements',
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, max_length=10, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('micr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_address', models.TextField(blank=True, null=True)),
                ('payee_acknowledgement', models.BooleanField(default=False, editable=False)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payees.payee')),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Details',
            },
        ),
    ]
