# Generated by Django 4.2.11 on 2026-02-20 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payee', to=settings.AUTH_USER_MODEL),
        ),
    ]
