# Generated by Django 4.2.11 on 2024-09-05 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
        ('payees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='tds_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs.tds', to_field='tds_legal_name'),
        ),
        migrations.DeleteModel(
            name='TDS',
        ),
    ]
