# Generated by Django 4.2.11 on 2024-12-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0002_alter_payee_tds_type_delete_tds'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='is_dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
