# Generated by Django 4.2.11 on 2025-01-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0003_payee_is_dark_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payee',
            options={'verbose_name': 'Payee'},
        ),
        migrations.AlterField(
            model_name='payee',
            name='is_dark_mode',
            field=models.BooleanField(default=False, help_text='Enable dark mode for a darker, low-light-friendly interface '),
        ),
    ]
