# Generated by Django 4.2.11 on 2025-04-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0004_alter_payee_options_alter_payee_is_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
