# Generated by Django 4.2.11 on 2024-09-05 04:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tds_legal_name', models.CharField(choices=[('technical-consultants', 'Technical Consultants'), ('professional-consultant', 'Professional Consultant'), ('employment', 'Employment'), ('apprentices', 'Apprentices')], max_length=50, unique=True)),
                ('tds_percentage', models.FloatField()),
            ],
            options={
                'verbose_name': 'Tax Deducted at Source',
                'verbose_name_plural': 'Tax Deducted at Source',
            },
        ),
    ]
