# Generated by Django 4.2.11 on 2024-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
                ('operation', models.CharField(choices=[('sum', 'Sum'), ('subtract', 'Subtract')], max_length=10)),
            ],
        ),
    ]
