# Generated by Django 4.2.11 on 2026-02-20 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='payroll/form16s/')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form16s', to='payees.payee')),
            ],
        ),
        migrations.CreateModel(
            name='PayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PayRecordRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='payroll/registers/')),
                ('pay_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='payroll.payrun')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('pay_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payroll.payrun')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payees.payee')),
            ],
        ),
        migrations.CreateModel(
            name='Form16Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('form16', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.form16')),
            ],
            options={
                'verbose_name': 'Form16 entry',
                'verbose_name_plural': 'Form16 entries',
            },
        ),
    ]
