# Generated by Django 4.2.11 on 2024-09-04 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField(default=2024)),
                ('status', models.CharField(choices=[('due', 'DUE'), ('in_progress', 'IN PROGRESS'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED'), ('approved', 'APPROVED')], default='due', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pay Run',
                'verbose_name_plural': 'Pay Runs',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label', models.CharField(max_length=50)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payees.payee')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PayRecordRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=16, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, max_length=10, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('micr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_address', models.TextField(blank=True, null=True)),
                ('tds_percentage', models.FloatField(blank=True, null=True)),
                ('pay_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.payrun')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payees.payee')),
            ],
            options={
                'verbose_name': 'Pay Record Register',
                'verbose_name_plural': 'Pay Record Registers',
                'ordering': ['-record_created'],
                'unique_together': {('payee', 'pay_run')},
            },
        ),
    ]
