# Generated by Django 4.2.11 on 2024-09-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0002_alter_payee_tds_type_delete_tds'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payees.payee'),
        ),
        migrations.AlterField(
            model_name='payrun',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payrun',
            name='year',
            field=models.IntegerField(),
        ),
    ]
