# Generated by Django 4.2.11 on 2024-09-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrun',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payrun',
            name='year',
            field=models.IntegerField(),
        ),
    ]
