# Generated by Django 4.2.11 on 2024-09-24 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_component'),
        ('payroll', '0002_alter_payment_payee_alter_payrun_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrecordregister',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ComponentValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.component')),
                ('pay_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrecordregister')),
            ],
        ),
    ]
