# Generated by Django 4.2.11 on 2025-04-07 06:55

from django.db import migrations, models
import django.db.models.deletion
import payroll.upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0004_alter_payee_options_alter_payee_is_dark_mode'),
        ('payroll', '0003_payrecordregister_gross_amount_componentvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(blank=True, max_length=10, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('form16_zip_file', models.FileField(upload_to='uploads/payroll/form16/', validators=[payroll.upload_helpers.validate_zip_file])),
                ('is_extracted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Form16Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_16', models.FileField(upload_to=payroll.upload_helpers.form16_extracted_path)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.form16')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payees.payee')),
            ],
        ),
    ]
