# Generated by Django 4.2.11 on 2025-04-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_form16_form16entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrecordregister',
            name='net_income',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
