# Generated by Django 4.2.11 on 2025-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrecordregister_net_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrun',
            name='error_log',
            field=models.TextField(blank=True, help_text='shows only if any error occur in payees data ', null=True),
        ),
    ]
