SecretProviderClass:
- name: youpayroll-envs
  namespace: youpayroll-[JIRA_ID]
  provider: vault
  parameters:
    roleName: "ygg-eks-v2-youpayroll-app-role"
    objects: |
      - objectName: "application.env"
        secretPath: "ygag-secrets/data/it/qa/youpayroll/env-uae"
        secretKey: "app-env"
      - objectName: "application-devops.env"
        secretPath: "ygag-secrets/data/devops/qa/external/it/youpayroll/env-uae"
        secretKey: "app-env"

- name: youpayroll-certs-sample1
  namespace: youpayroll-[JIRA_ID]
  provider: vault
  parameters:
    roleName: "ygg-eks-v2-youpayroll-app-role"
    objects: |
      - objectName: "certificate.pem"
        secretPath: "ygag-secrets/data/it/qa/youpayroll/certs-sample1"
        secretKey: "certificate.pem"
      - objectName: "private.key"
        secretPath: "ygag-secrets/data/it/qa/youpayroll/certs-sample1"
        secretKey: "private.key"

- name: youpayroll-certs-sample2
  namespace: youpayroll-[JIRA_ID]
  provider: vault
  parameters:
    roleName: "ygg-eks-v2-youpayroll-app-role"
    objects: |
      - objectName: "certificate.pem"
        secretPath: "ygag-secrets/data/it/qa/youpayroll/certs-sample2"
        secretKey: "certificate.pem"
      - objectName: "private.key"
        secretPath: "ygag-secrets/data/it/qa/youpayroll/certs-sample2"
        secretKey: "private.key"
      - objectName: "private2.key"
        secretPath: "ygag-secrets/data/it/qa/youpayroll/certs-sample2"
        secretKey: "private2.key"
      - objectName: "private3.key"
        secretPath: "ygag-secrets/data/it/qa/youpayroll/certs-sample2"
        secretKey: "private3.key"
      - objectName: "private4.key"
        secretPath: "ygag-secrets/data/it/qa/youpayroll/certs-sample2"
        secretKey: "private4.key"

- name: youpayroll-certs-sample-client3
  namespace: youpayroll-[JIRA_ID]
  provider: vault
  parameters:
    roleName: "ygg-eks-v2-youpayroll-app-role"
    objects: |
      - objectName: "certificate.pem"
        secretPath: "ygag-secrets/data/it/qa/youpayroll/certs-sample-client3"
        secretKey: "certificate.pem"
      - objectName: "private.key"
        secretPath: "ygag-secrets/data/it/qa/youpayroll/certs-sample-client3"
        secretKey: "private.key"